# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9de4ed7c1c6408e906ceb129d85548b43aed1bf1be7a7ce8718914cc8f4c942d7bc9e87a50f100b96ecb24901b76c33cdb3b1ec775a8b83c3fd7002779143dec

test:
  secret_key_base: 3a96d6c2ebb56b15766d675a9b5c27864e9382a14fc90d157c1fa05b6c6a3d0f9f7b992fdead608030d6da9aa62cd26f88e9119d8f8334319a3ff5fbf9afa5e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
